package com.example.petcare;
import android.widget.AdapterView;
import java.util.HashMap;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.ListView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import java.util.ArrayList;




public class ListActivity extends AppCompatActivity {


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_list);

        Toolbar toolbar = findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        getSupportActionBar().setDisplayShowTitleEnabled(false);


        ImageView backImageView = findViewById(R.id.logoImageView1);
        backImageView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                onBackPressed();
            }
        });

        Intent intent = getIntent();
        if (intent != null && intent.hasExtra("CATEGORY")) {
            final String category = intent.getStringExtra("CATEGORY");

            ListView listView;
            if ("Psi".equals(category)) {
                listView = findViewById(R.id.listViewDogs);
            } else if ("Mačke".equals(category)) {
                listView = findViewById(R.id.listViewCats);
            } else if ("Ptice".equals(category)) {
                listView = findViewById(R.id.listViewBirds);
            } else if ("Glodavci".equals(category)) {
                listView = findViewById(R.id.listViewRodents);
            } else if ("Ribe".equals(category)) {
                listView = findViewById(R.id.listViewFishes);
            } else {
                Toast.makeText(this, "Nepoznata kategorija", Toast.LENGTH_SHORT).show();
                finish();
                return;
            }

            ArrayList<ListItem> dataList = getDataForCategory(category);
            CustomListAdapter adapter = new CustomListAdapter(this, R.layout.list_item, dataList);


            listView.setVisibility(View.VISIBLE);

            listView.setAdapter(adapter);

            listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
                @Override
                public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                    ListItem selectedItem = dataList.get(position);
                    showDetailsActivity(selectedItem);
                }
            });


        } else {
            Toast.makeText(this, "Nije odabrana kategorija", Toast.LENGTH_SHORT).show();
            finish();
        }
    }


    private ArrayList<ListItem> getDataForCategory(String category) {
        ArrayList<ListItem> dataList = new ArrayList<>();

        if ("Psi".equals(category)) {
            dataList.add(new ListItem("Pudle", R.drawable.pudla, "Pudle\n\nPostoje tri veličine pudli - velike, srednje i patuljaste. Velike pudle su veoma energične i inteligentne, često se koriste kao psi za traganje i spasavanje. Srednje pudle su prilagodljive i dobre u učenju trikova, dok su patuljaste pudle male i slatke, odlične kao kućni ljubimci.\n\nPudle su takođe poznate po svojoj dugovječnosti i niskom procentu alergija. One su poznate po svom kovrdžavom krznu i pametnom temperamentu. Pudle su vrlo inteligentne, druželjubive i vesele. Takođe, one su i veoma prilagodljive.\n\nS pudlom se treba baviti i učiti je raznim trikovima. Pudle se vole igrati i vole udovoljavati svojim vlasnicima. Jako paze na svoje ljude i uvijek će upozoriti lavežom na nepoznate ljude. Pošto su pametne gotovo kao ljudi, brzo uče. Jako je važno da pudlu naučiš dobrom ponašanju, jer će biti izazov jednoj takvoj pametnici promijeniti životni stil. Jako dobro pamte.\n\nTvoja će pudla najviše uživati u svojim iskonskim nagonima – plivanju i vraćanju stvari poput bačenih loptica.\n " ));
            dataList.add(new ListItem("Kavalirski kral Charles španijeli", R.drawable.pas2,"Kavalirski kral Charles španijeli\n\nKavalirski kral Charles španijeli su rasa pasa koja potiče iz Engleske. Oni su ime dobili po kralju Charlesu II koji je bio veliki ljubitelj ove rase.\n\nKavalirski kral Charles španijeli su poznati po svojoj ljubaznosti, veselosti i prijateljskom temperamentu. Oni su odlični porodični psi i vole da se maze i igraju. Takođe, ova rasa je veoma inteligentna i lako se obučava.  Oni su poznati po svojoj ljupkoj i prijateljskoj naravi.\n\nKavalirski kral Charles španijeli su mali psi sa dugim, svilenkastim krznom i izražajnim očima. Oni su veoma privrženi i vole da budu u društvu ljudi. Ova rasa je takođe poznata po svojoj blagosti i prijateljskom karakteru.\n"));
            dataList.add(new ListItem("Francuski buldozi", R.drawable.pas3,"Francuski buldozi\n\nSvojom kratkom, zdepastom građom, francuski buldog odaje dojam mišićavog malog psa. On teži od 8 do 14 kg na visinu grebena od oko 30 cm. Upečatljive su velike, uspravne uši postavljene na četvrtastu glavu, kao i karakteristična kratka njuška i rep. Sjajna dlaka bez poddlake dolazi u raznim bojama, od uobičajenih tonova poput crne ili bijele do smeđe, krem ili tamnocrvene boje.\n\nFrancuski buldozi vrlo su simpatični i veseli psi. Pametni su, druželjubivi, vole da ih se mazi i prikladni su čak i za vlasnike početnike. Nažalost, zbog nedostatka zraka često preferiraju kratke šetnje i rijetko laju. U pravilu se dobro slažu s ostalim ljubimcima, razigrani su i pažljivi. Također se smatraju ljubiteljima djece i nemaju razvijen lovački instinkt zbog čega se obično dobro slažu s mačkama koje žive u kućanstvu.\n\nFrancuski buldog odgovara svim umjereno aktivnim ljubiteljima pasa. Pripadnici ovoj pasmini pogodni su za porodice kao i za samce, a također su odličan izbor za vlasnike početnike. Starije osobe koje vole šetati odlično će se složiti s francuskim buldogom.\n "));
            dataList.add(new ListItem("Džek Rasel terijeri", R.drawable.pas4,"Džek Rasel terijeri\n\nDžek Rasel terijeri potiču iz Engleske. Ime su dobili po svom osnivaču, Rev. Džeku Raselu, koji je bio pasionirani uzgajivač ove rase. On je želio da stvori terijera koji bi bio vješt u lovu na lisice, ali istovremeno i odan i prijateljski nastrojen prema ljudima.\n\nDžek Rasel terijeri su veoma svestrani psi. Oni su poznati po svojoj sposobnosti da se takmiče u raznim aktivnostima poput agilitija i takmičenja u poslušnosti. Takođe su odlični kao kućni ljubimci jer su veoma odani i privrženi svojim vlasnicima.\n\nDžek Rasel terijeri su veoma inteligentni i vole da budu mentalno stimulisani, pa je važno pružiti im dovoljno mentalne i fizičke aktivnosti.\n"));
            dataList.add(new ListItem("Maltezeri", R.drawable.pas5,"Maltezeri\n\nMaltezeri potiču sa Mediterana, tačnije sa ostrva Malte. Ova rasa je veoma stara i ima bogatu istoriju.\n\nMaltezeri su poznati po svom dugom, svilenkastom krznu i živahnom karakteru. Oni su veoma društveni i vole da budu u centru pažnje. Maltezeri su mali, ali hrabri psi koji su poznati po svojoj ljupkosti. Oni su veoma inteligentni i lako se obučavaju. Maltezeri su takođe veoma prijateljski nastrojeni i vole da provode vrijeme sa svojim vlasnicima. Njihova duga, svilenkasta dlaka zahtjeva redovno četkanje i održavanje.\n\nOva rasa je veoma popularna kao kućni ljubimci zbog svoje nježne prirode i ljubavi prema ljudima. Vrlo su jednostavni i nezahtjevni. Bilo da je riječ o zajedničkoj igri, odlasku na izlete ili izležavanju, maltezer uvijek širi dobro raspoloženje, glavno je da je uz njega njegov vlasnik.\n"));
            dataList.add(new ListItem("Ši-cu", R.drawable.pas6,"Ši-cu\n\nPsi rase Ši-cu potiču iz Kine. Ši-cu je veoma stara rasa koja se smatra svetom u kineskoj kulturi. Oni su bili omiljeni ljubimci kineskih careva i često su ih držali u carskim dvorovima.\n\nŠi - cu je dugodlaki, snažan pas koji može biti raznih boja. Kreću se prilično arogantno s repom preko leđa. Visina odraslog ši-cua ne bi trebalo da bude veća od 27 cm, a idealna težina je 4,5-7,5 kg.\n\nOvi psi su veoma privrženi svojim vlasnicima i vole da budu u centru pažnje. Njihova duga, svilenkasta dlaka zahtijeva redovno četkanje i održavanje. Ši-cu su idealni za ljude koji žive u stanovima ili manjim prostorima, jer su prilagodljivi i ne zahtjevaju puno fizičke aktivnosti.\n"));
            dataList.add(new ListItem("Bostonski terijer ", R.drawable.pas7,"Bostonski terijer\n\nBostonski terijer potiče iz Sjedinjenih Američkih Država. Ova rasa je nastala u 19. vijeku u Bostonu, odakle i dolazi njeno ime.\n\nBostonski terijer spada u dogolike pse i odlikuje se kompaktnim izgledom, četvrtastom, snažnom glavom i karakteristično postavljenim šišmišolikim ušima, kratkim nosom i zdepastim repom.\n\n U standardu pasmine se velika važnost pridaje ravnoteži proporcija, pri čemu je bostonski terijer dostupan u tri kategorije – ispod 6,8 kg (lagani), od 6,9 do 9 kg (srednji) i konačno od 9 do 11,3 kg (teški). Najveća visina u grebenu je oko 43 cm. Lice je bez bora, a kratka, sjajna dlaka bez poddlake može biti tigrasta, crna ili seal boje (crna s crvenkastom nijansom) s raznim uzorcima i bijelim dijelovima dlake koji su obavezni.\n\nBostonski terijeri su poznati po svojoj živahnoj i prijateljskoj prirodi. Oni su odani i vole da budu u društvu svojih vlasnika. Ovi psi su takođe veoma inteligentni i lako se obučavaju. Bostonski terijeri su sjajni kućni ljubimci za porodice i pojedince koji žive u stanovima.\n  "));
            dataList.add(new ListItem("Bichon Frise", R.drawable.pas8,"Bichon Frise\n\nBichon Frise psi potiču sa Mediterana, tačnije sa ostrva Malte. Zato se često nazivaju i „Malteški psi“.\n\nPripadnici ove pasmine imaju maksimalnu težinu od 6 kg i visinu grebena oko 30 cm. Isključivo bijela dlaka može biti dugačka do 10 cm. Svilenkast je i gladak, a izgleda posebno meko zahvaljujući kovrčama. Gornja dlaka je, međutim, nešto oštrija.\n\nBichon Frise su veoma prijateljski nastrojeni i vole da budu u centru pažnje. Takođe, oni su odlični kućni ljubimci za porodice i ljude svih uzrasta. Bichon Frise psi su poznati po svom nealergijskom krznu, što ih čini odličnim izborom za ljude koji imaju alergije na dlaku pasa.\n"));
            dataList.add(new ListItem("Šetlandski ovčar", R.drawable.pas9,"Šetlandski ovčar\n\nSetlandski ovčar, poznat i kao šetlandski ovčar, je prelijep pas koji potiče sa Šetlandskih ostrva u Škotskoj.\n\nŠetlandski ovčar ima atraktivno, dugačko krzno sa obilnom grivom oko vrata i grudi i obilnom paperijastom dužom dlakom na nogama i repu. Krzno može biti u nekoliko boja, uzoraka i kombinacija boja. Odrasli mužjaci imaju otprilike 37 cm, a ženke 35,5 cm. Težina potpuno odraslog šetlandskog ovčara kreće se od 6-12 kg.\n\nSetlandski ovčari su veoma inteligentni, poslušni i lako se obučavaju. Takođe su veoma energični i vole da budu aktivni. Ovi psi su odani i dobrodušni, što ih čini odličnim kućnim ljubimcima.\n"));
            dataList.add(new ListItem("Pekinezer ", R.drawable.pas10,"Pekinezer\n\nPekinezeri su pripadnici najstarije rase pasa, a nastali su u Kini. Njihovo ime dolazi iz grada Pekinga.\n\nVećina pekinezera ima dugu svilenu dlaku. Boje su najčešće crna, bijela, smeđa, žuta te narandžasta. Njuška im je tupa i vrh tartufa hrapav. Oči su velike i izbočene. Pekinezeri imaju dug jezik koji za vrijeme ljeta neprekidno viri iz usta. Rep im je najčešće kitnjast i dug, dok se mogu naći i drugačije varijante.\n\nPekinezeri su veoma privrženi i vole da budu u centru pažnje. Iako su mali, imaju hrabar i samouvjeren karakter. Oni su odlični kućni ljubimci za one koji žive u stanovima, jer ne zahtjevaju puno fizičke aktivnosti.\n"));
        } else if ("Mačke".equals(category)) {
            dataList.add(new ListItem("Perzijska mačka", R.drawable.macka1,"Perzijska mačka\n\nDuga, mekana dlaka s puno poddlake jedna je od karakteristika perzijske mačke. Nije svaka mačka s dugom dlakom perzijska mačka. Izgled perzijske mačke oblikuju tri udruge uzgajivača koje daju prioritet različitim osobinama.\n\nU pravilu je perzijska mačka, mačka srednje veličine ili velika mačka. Mužjaci teže do 7 kg, ženke do 6 kg. Tijelo podupiru niske, zdepaste noge. Pramenovi dlake između kandži okruglih šapa svakako su poželjni. Osim duge dlake, za ovu pasminu tipično je i lice. Na širokoj lobanji nalaze se okrugle uši s čupercima dlake i vrlo kratak nos.\n\nDvobojne i trobojne perzijske mačke vrlo su popularne, kao i perzijske mačke egzotične smoke boje. Dok je veći dio dlake obojen, korijen dlake mačke je srebrno-bijeli. Ako su samo vrhovi obojeni i ako je većina dlake srebrno-siva, onda se radi o varijanti boje shaded.\n\nOve mačke su veoma elegantne i mirne, te često djeluju kao prave male princeze. Perzijske mačke su nježne i privržene, ali mogu biti malo rezervisane prema nepoznatim ljudima. Zahtjevaju redovno četkanje kako bi se održalo njihovo krzno u dobrom stanju. Ove mačke su odlični kućni ljubimci za one koji vole mirnije i nježnije mačke.\n"));
            dataList.add(new ListItem("Sijamska mačka", R.drawable.macka2,"Sijamska mačka\n\nVisina ramena sijamske mačke doseže od 20 do 25 centimetara. Ženke teže tri do četiri kilograma. Mužjaci, pak, mogu biti teški i do pet kilograma. Uz njihovu atletsku građu, dugačak, ravan nos i upečatljiv oblik glave nepogrešive su karakteristike pasmine sijamske mačke. Glava je klinastog oblika i blago konveksna gledano sa strane. Uspravne, široke uši izdužuju mačje lice koje izgleda gotovo trokutasto.  Duboko plave oči u obliku badema koje su široko razmaknute i blago nakošene također su tipične. Plava boja je posljedica činjenice da su sijamske mačke djelomično albino. Proizvode samo malu količinu pigmenta melanina, što je i razlog posebne boje dlake.\n\nOne su veoma vokalne i često će se javljati svojim karakterističnim glasom. Sijamske mačke su odlični kućni ljubimci za one koji vole mačke sa živahnim i razigranim karakterom.\n "));
            dataList.add(new ListItem("Maine Coon", R.drawable.macka3,"Maine Coon\n\nMaine coon mačka je poludugodlaka mačka. Izvorno dolazi sa sjeveroistoka SAD-a, područja s dugim, hladnim zimama. Zbog svog podrijetla ima vodoodbojnu dlaku s čvrstom naddlakom i gustom poddlakom.\n\nOve mačke imaju velike, šiljate uši koje na kraju imaju čuperke dlake, slično risu. Između šapa strše čuperci dlake, takozvane krplje. Uzgajivači prihvaćaju gotovo sve boje i uzorke dlake pasmine maine coon. Jedino nije poželjna boja dlake gold (bež dlaka s crnim vrhovima) i prošarani uzorak (raznobojna dlaka).  Lijepe oči ovih mačaka su velike i jasne, njihova boja treba odgovarati dlaci.\n\nMaine Coon mačke su veoma društvene, inteligentne i vole da se igraju. Imaju prijateljski i nježan temperament, što ih čini odličnim kućnim ljubimcima. Legenda kaže da su se ove mačke ukrstile sa divljim mačkama, ali ta priča nije potvrđena.\n"));
            dataList.add(new ListItem("Britanska kratkodlaka mačka", R.drawable.macka4,"Britanska kratkodlaka mačka\n\nBritanska kratkodlaka mačka je prelijepa rasa mačaka koja potiče iz Velike Britanije.\n\nOve mačke su poznate po svom snažnom i mišićavom tijelu, debelom krznu i širokom licu sa izraženim obrazima. U pravilu, ova mačka nije u potpunosti izrasla do treće godine života. Ženka tada teži i do 5 kg, a mužjak i do 7 kg. U većini slučaja ove su mačke zdrave te kod pravilne njege i prehrane mogu živjeti najmanje 15 godina.\n\nBritanske kratkodlake mačke su veoma mirne, umiljate i društvene. One su odlični kućni ljubimci za porodice i vole da se maze. Takođe, ove mačke su poznate po svojoj nezavisnosti i samostalnosti.\n "));
            dataList.add(new ListItem("Sibirska mačka", R.drawable.macka5,"Sibirska mačka\n\nSibirska mačka potiče iz Rusije, tačnije sa područja Sibira. Ova rasa mačaka je razvijena u prirodnim uslovima, a poznata je po svojoj izdržljivosti i prilagodljivosti hladnim klimatskim uslovima.\n\nSibirske mačke imaju gustu dlaku koja ih štiti od hladnoće, a takođe imaju i snažno tijelo i snažne šape. Sibirske mačke mogu biti dugačke do 120 cm s 30-35 cm u ramenima. Mačke srednje veličine su mišićave i teške do devet kilograma. Zato nisu u potpunosti odrasle dok ne navrše oko tri godine.\n\nOve mačke su veoma društvene, inteligentne i vole da se igraju. Sibirske mačke su odlični kućni ljubimci za one koji vole mačke sa divnom dlakom i prijateljskim temperamentom.\n"));
            dataList.add(new ListItem("Ragdoll mačka", R.drawable.macka6,"Ragdoll mačka\n\nRagdoll mačka je predivna rasa mačaka koja potiče iz Sjedinjenih Američkih Država. Ove mačke su poznate po svojoj mirnoj i umiljatoj prirodi. Ime \"Ragdoll\" dolazi od njihovog karakterističnog ponašanja kada se opuste u rukama vlasnika, poput \"krpene lutke\".\n\nRagdoll mačke imaju srednje dugu, svilenkastu dlaku i dolaze u različitim bojama i šarama. One su takođe veoma velike mačke, sa snažnim tijelom i lijepim plavim očima. Ragdoll mačka je jedna od velikih pasmina mačaka. Ženke su teške do 6,5 kilograma, mužjaci do 9,5 kilograma. Uz visinu ramena do 40 centimetara, ove mačke također dosežu dužinu do 1,20 metara od vrha nosa do vrha repa.\n\nRagdoll mačke su odlični kućni ljubimci koji su ljubazni, privrženi i vole da se maze.\n "));
            dataList.add(new ListItem("Egipatska Mau mačka", R.drawable.macka7,"Egipatska Mau mačka\n\nEgipatska Mau mačka je fascinantna rasa mačaka koja potiče iz Egipta. Ove mačke su poznate po svojoj elegantnoj i mišićavoj građi, kao i po svojoj prelijepoj i šarenoj dlaci. Mau mačke su jedine rase mačaka koje imaju prirodno šarene tačke na krznu. Takođe, ove mačke su veoma brze i okretne, što ih čini sjajnim lovcima.\n\nEgipatska mau najbrža je od svih mačaka. Može trčati i do 50 kilometara na sat. Kako bi mogla trošiti energiju na prikladan način, vrlo je važno da je egipatska mau vrlo aktivna.\n\nEgipatske Mau mačke su inteligentne, društvene i vole da budu u centru pažnje. One su odlični kućni ljubimci za one koji vole aktivne i igračke mačke.\n"));
            dataList.add(new ListItem("Abyssinian mačka", R.drawable.macka8,"Abyssinian mačka\n\nAbyssinian mačka je predivna rasa mačaka koja potiče iz Etiopije, koja se nekada nazivala Abisinija.\n\nOva mačka nalikuje na pumu, iako u znatno manjoj mjeri. Ove mačke su poznate po svojoj kratkoj, mekoj dlaci i prelijepim bojama. Abyssinian mačke imaju sjajnu, tigrastu šaru koja im daje divan izgled. Abyssinian dolazi u različitim bojama, uključujući smeđu, crnu, plavu, crvenu, krem, i srebrnu. Postoje i različite nijanse unutar svake boje. Vrlo su karakteristične tople smeđe, zelene ili zlatne oči. Glava Abyssinian mačke je srednje veličine, široka, ali ne previše zaobljena. Njuška je četvrtasta, s blago zakrivljenim profilom. Uši su velike i špicaste, stoje uspravno na glavi. Oči Abyssiniana su velike, okrugle do bademastog oblika, i postavljene su široko jedno od drugog. Rep Abyssiniana je srednje dužine, tanak pri osnovi, postepeno se sužava prema vrhu.\n\nOne su takođe veoma aktivne, znatiželjne i inteligentne. Abyssinian mačke su odlični kućni ljubimci za one koji vole mačke koje su puna energije i koje vole da se igraju.\n"));
            dataList.add(new ListItem("Burmanska mačka", R.drawable.macka9,"Burmanska mačka\n\nBurmanska mačka je predivna rasa mačaka koja potiče iz Burme, današnje Mjanmarske. Ove mačke su poznate po svojoj dugoj i svilenkastoj dlaci, kao i po svojim intenzivnim plavim očima.\n\nKao orijentalna pasmina mačaka, burmanske mačke vrlo su inteligentne. Također su posebno zainteresovane i zaigrane. Povjerljive mačke u potpunosti prihvataju ljude. Vrlo su razigrane i vole biti u društvu mlađih članova porodice.\n\nBurmanske mačke su takođe poznate po svojoj mirnoj i nežnoj prirodi. Burmanske mačke su sjajni kućni ljubimci za one koji žele mačku koja je ljubazna i društvena.\n  "));
            dataList.add(new ListItem("Scottish Fold mačka", R.drawable.macka10,"Scottish Fold mačka\n\nScottish Fold mačka je predivna rasa mačaka koja je poznata po svojim preklopljenim ušima. Ova rasa potiče iz Škotske, kao što i ime sugeriše.\n\nScottish Fold mačke imaju mekanu i gusta dlaku, a njihove preklopljene uši im daju poseban izgled. Škotski fold pasmina je srednje veličine punašnog tijela i nabijenih nogu. Njihov je rep srednje dužine do dugačak, ali bi uvijek trebao biti proporcionalan s tijelom, a na kraju zašiljen. Krzno škotskog folda je gusto i mekano. Srednje je dužine, a varijanta highland fold ima nešto dužu dlaku. Ženka teži između dva i četiri kilograma, a mužjak između četiri i pet kilograma.\n\nOne su takođe poznate po svojoj mirnoj i ljubaznoj prirodi. Škotski fold je mačka iznimno mirne naravi koja rijetko mijauče. Scottish Fold mačke su odlični kućni ljubimci za one koji vole mačke koje su nježne i društvene.\n "));
        } else if ("Ptice".equals(category)) {
            dataList.add(new ListItem("Kanarinke", R.drawable.ptica1,"Kanarinke\n\nKanarinke su predivne ptice koje su poznate po svojim veselim pjesmama i šarenim perjem. One potiču sa Kanarskih ostrva, odakle su i dobile ime. Kanarinke su popularni kućni ljubimci zbog svog prelijepog izgleda i melodioznog pjevanja.\n\nMužjaci kanarinaca obično imaju živopisno perje. Boje perja mogu varirati od svijetložute, preko narandžaste, crvene, zelene, pa do plave i ljubičaste. Mnogi kanarinci imaju različite kombinacije boja i šara, uključujući i perje na glavi koje može biti različito oblikovano, poput šešira. Neki mužjaci imaju izražene crte na licu ili krilima.\n\nŽenke kanarinaca su obično manje upadljive u boji, često su smeđe ili sive. Njihovo perje često nema istu intenzitet boja kao kod mužjaka, ali takođe mogu imati lijepe nijanse. Ženke obično nemaju tako izražene crte na licu kao mužjaci. Mužjaci kanarinke obično imaju jače i raznovrsnije pesme od ženki.\n\nOne su relativno jednostavne za njegu i mogu biti veoma prijateljske i društvene. Kanarinke su sjajne ptice za one koji žele da uživaju u njihovom prelijepom pjevanju i živopisnom izgledu.\n"));
            dataList.add(new ListItem("Papagaj Nimfa", R.drawable.ptica2,"Papagaj Nimfa\n\nNimfe su porijeklom iz Australije i često se drže kao kućni ljubimci. Nimfa papagaj je manja ptica, obično duga oko 30 cm, uključujući rep. Njeno tijelo je snažno i kompaktno. Nimfa ima meko perje koje može biti raznovrsnih boja. Tipično, boje uključuju zelenu, plavu, žutu, sivu, bijelu i crnu, ali postoje i različite varijacije koje su rezultat selektivnog uzgoja.\n\nKarakteristično za nimfe je bijelo perje oko očiju i na obrazima, stvarajući masku koja može izgledati poput obraza pokrivenih prašinom. Kljun nimfe je snažan i karakterističan, često zakrivljen prema dole. Boja kljuna može varirati od crne do svijetlosive. Oči nimfe su obično tamne, a izražaj lica može varirati od ozbiljnog do razigranog, zavisno o raspoloženju ptice. Rep nimfe je prilično dugačak u odnosu na tijelo i obično je sastavljen od pera različitih boja. Noge nimfe su kratke i snažne, a stopala su često sivkasta.\n\nNimfe su poznate po svojoj živopisnoj pojavi i ljubaznom karakteru. One su društvene ptice koje često formiraju snažne veze sa svojim vlasnicima. Osim toga, nimfe su poznate po svojim živahnim pokretima i sposobnosti da uče različite zvuke i riječi.\n"));
            dataList.add(new ListItem("Agapornis", R.drawable.ptica3,"Agapornis\n\nAgapornisi su mali papagaji, obično dugi oko 15-17 cm, uključujući rep. Njihovo tijelo je kompaktno, a rep je često kratak i zaobljen. Agapornisi imaju gustu i meku dlaku koja može biti raznovrsnih boja. Tipično, boje uključuju zelenu, plavu, žutu, crvenu i ljubičastu.\n\nKarakteristično za agapornise je odsustvo bijelog perja oko očiju, za razliku od nekih drugih vrsta papagaja. Njihovo lice često ima intenzivne boje, stvarajući jasnu razliku od perja na telu. Kljun agapornisa je srednje veličine, snažan i često zakrivljen prema dole. Boja kljuna može varirati od crne do svijetlosive. Oči agapornisa su obično tamne i izražene. Rep agapornisa je obično kratak i zaobljen, stvarajući simpatičan izgled.  Noge agapornisa su kratke i snažne, a stopala su obično sive boje.\n\nAgapornisi su poznati po svojoj ljubavi prema društvu i često formiraju snažne emocionalne veze sa svojim vlasnicima. Ovi papagaji su poznati i po svojoj socijalnoj prirodi i sklonošću da žive u paru.\n"));
            dataList.add(new ListItem("Budgerigar", R.drawable.ptica4,"Budgerigar\n\n Budžerigari su mali papagaji, obično dugi oko 18 cm, uključujući rep. Njihovo tijelo je vitko i ima aerodinamički oblik. Perje budžerigara može biti raznovrsnih boja, uključujući svijetloplavu, žutu, zelenu, crvenu i crnu.\n\nMužjaci često imaju nosivu boju perja na nosu. Lice budžerigara je često prekriveno tanjim perjem i može imati crtu preko očiju. Oči su obično tamne i sjajne. Kljun budžerigara je kratak, snažan i često blago zakrivljen. Boja kljuna može varirati od crne do svijetlosive, zavisno o boji perja. Oči budžerigara su obično crne, a izražaj lica može varirati zavisno o emocijama ptice. Rep budžerigara je dug i ima karakterističan oblik. Boje perja na repu često se podudaraju s bojom perja na tijelu.  Noge budžerigara su kratke i snažne, a stopala su obično sive boje.\n\nBudžerigari su popularni kao kućni ljubimci zbog svoje inteligencije i mogućnosti da nauče različite zvuke i riječi. Takođe su društveni i vole interakciju sa svojim vlasnicima.\n"));
            dataList.add(new ListItem("Ara papagaj", R.drawable.ptica5,"Ara papagaj\n\nAre su obično srednje do velike ptice, sa značajnom dužinom tijela i repa. Ova vrsta papagaja karakteristična je po svojim živopisnim i jarkim bojama perja. Boje uključuju crvenu, zelenu, plavu, žutu, narandžastu i druge nijanse. Imaju snažan kljun koji je često kratak i zakrivljen, savršen za lomljenje orašastih plodova i voća.\n\nRep ara papagaja može biti dugačak i vitak, a neke vrste imaju repove sa šiljcima. Oči ara obično imaju tamnu boju, a izraz lica može varirati zavisno o raspoloženju ptice. Imaju snažan vrat koji često nosi kontrastne šare ili boje. Noge ara su snažne i imaju snažne kandže koje su korisne za penjanje i držanje hrane.\n\nVažno je napomenuti da postoji veliki broj vrsta ara, a svaka vrsta ima svoje specifične karakteristike i boje perja. Veće vrste ara, poput plavokrilatih ara ili ara makaoa, obično zahtjevaju više prostora i posebnu pažnju u domaćinstvu. Kada se razmatra držanje are kao kućnog ljubimca, važno je pružiti odgovarajući prostor, ishranu i društvo kako bi ptica bila srećna i zdrava.\n"));
            dataList.add(new ListItem("Kardinal", R.drawable.ptica6,"Kardinal\n\nKardinali su obično srednje veličine, sa snažnim tijelom i kratkim, snažnim kljunom. Mužjaci obično imaju jarke boje, dok su ženke često manje šarene.\n\nMužjaci kardinala su poznati po svojim živopisnim crvenim perjem. Ovo crveno perje obično prekriva tijelo, glavu i rep mužjaka.\n\nŽenke su obično smeđe ili sive boje, sa manje izraženom crvenom bojom. Kardinali imaju snažan, konusni kljun koji im pomaže u hranjenju različitih vrsta sjemena i insekata.\n\nKardinali su omiljeni među posmatračima ptica i predstavljaju simbol sreće i vedrine.\n"));
            dataList.add(new ListItem("Ljubimac ljubičast", R.drawable.ptica7,"Ljubimac ljubičast\n\nPtica ljubimac ljubičasti koju možete imati je ljubičasti finik. Ljubičasti finik je prelijepa ptica sa svijetlim ljubičastim perjem.\n\nOni su veoma društveni i inteligentni ljubimci, a mogu naučiti da ponavljaju riječi i izvode razne trikove. Takođe su veoma aktivni i vole da lete i istražuju svoje okruženje.\n\nAko razmišljate o nabavci ljubičastog finika, trebali biste biti spremni da im pružite puno pažnje i brige, ali će vam oni zasigurno donijeti puno radosti i zabave.\n\nLjubičasti finik potiče iz Južne Amerike, tačnije iz područja uključujući Venecuelu, Kolumbiju i Ekvador. To su tropske ptice koje se mogu naći u šumama i močvarama.\n"));
            dataList.add(new ListItem("Zebrice", R.drawable.ptica8,"Zebrice\n\nZebrice su predivne ptice koje potiču iz Australije. One su vrlo popularni kućni ljubimci zbog svog živopisnog izgleda i živahnog karaktera.\n\nZebrice su obično male veličine i imaju prugasto perje u različitim bojama poput plave, zelene, žute i bijele.\n\nOne su vrlo društvene i mogu biti veoma interaktivne ako se pravilno socijalizuju. Zebrice su takođe poznate po svom veselom i živahnom pjevu. Uz pravilnu brigu i pažnju, zebrica može biti sjajan dodatak svakom domu.\n"));
            dataList.add(new ListItem("Konur ", R.drawable.ptica9,"Konur\n\nKonuri su obično manje ptice u usporedbi s većim papagajima poput ara ili kakadua. Dužina tijela može varirati između 25 i 30 cm, ovisno o vrsti. Boje perja kod konura su vrlo raznolike. Ove ptice često imaju svijetlo i živopisno perje, uključujući nijanse zelene, plave, crvene, narandžaste i žute.\n\nPerje može imati različite šare i kombinacije boja. Kljun konura je srednje veličine, obično proporcionalan veličini tijela. Boja kljuna varira, ali obično ide od crne do sive. Oči konura su obično tamne i izražene. Glava konura često ima karakterističan oblik i može imati pernate šiljke koje se podižu ili spuštaju. Rep konura obično nije vrlo dug, ali može imati određene karakteristike kao što su šiljci ili boje koje čine rep upadljivim. Noge konura su obično snažne, a stopala imaju snažne kandže koje su korisne za penjanje.\n\nKonuri su često energični i društveni, a mnogi od njih su i dobri imitatori zvukova. Imaju srednje veličine i često se smatraju odgovarajućim kućnim ljubimcima za vlasnike koji žive u stanovima ili manjim domovima.\n" ));
            dataList.add(new ListItem("Kakadu", R.drawable.ptica10,"Kakadu\n\nKakadui mogu varirati u veličini, ali mnoge vrste su srednje do velike ptice, s dužinom tela obično između 30 i 60 cm. Boje perja kod kakadua su raznolike, a mogu uključivati bijelu, crvenu, roze, žutu, plavu i sivu.\n\nNeki kakadui imaju kontrastne šare na krilima, repu ili glavi. Kakadui imaju snažan kljun, često kratak i zakrivljen. Boja kljuna može varirati ovisno o vrsti, ali obično ide od crne do sive. Oči kakadua su obično tamne i izražene, a oko očiju može biti perja koje dodatno ističe njihov izgled.\n\nGlava kod mnogih vrsta kakadua ima karakteristične pernate šiljke, koji se mogu podići ili spustiti ovisno o raspoloženju ptice. Rep kakadua često ima dugačak i perjast izgled, često završava sa šiljcima. Noge su često jake i opremljene jakim kandžama koje omogućuju ptici da se penje i drži na granama.\n\nVažno je napomenuti da svaka vrsta kakadua ima svoje specifičnosti u izgledu, tako da detalji mogu varirati. Neke vrste, kao što su Sulphur-crested Kakadu ili Moluccan Kakadu, imaju vrlo prepoznatljiv izgled. Kakadui su takođe poznati po svojoj dugovečnosti i inteligenciji, ali zahtjevaju puno pažnje, stimulacije i odgovarajuću brigu kako bi bili srećni kao kućni ljubimci.\n"));
        } else if ("Glodavci".equals(category)) {
            dataList.add(new ListItem("Hrčak", R.drawable.glodavac1,""));
            dataList.add(new ListItem("Zec", R.drawable.glodavac2,""));
            dataList.add(new ListItem("Kunić ", R.drawable.glodavac3,""));
            dataList.add(new ListItem("Kunić ", R.drawable.glodavac4,""));
            dataList.add(new ListItem("Miševi", R.drawable.glodavac5,""));
            dataList.add(new ListItem("Gerbili", R.drawable.glodavac6,""));
            dataList.add(new ListItem("Degu", R.drawable.glodavac7,""));
            dataList.add(new ListItem("Prerijski pas", R.drawable.glodavac8,""));
            dataList.add(new ListItem("Hrčak roborovski", R.drawable.glodavac9,""));
            dataList.add(new ListItem("Činčile", R.drawable.glodavac10,""));
        } else if ("Ribe".equals(category)) {
            dataList.add(new ListItem("Zlatna ribica", R.drawable.riba1,""));
            dataList.add(new ListItem("Betta riba", R.drawable.riba2,""));
            dataList.add(new ListItem("Moli riba ", R.drawable.riba3,""));
            dataList.add(new ListItem("Gupi riba ", R.drawable.riba4,""));
            dataList.add(new ListItem("Neonska riba", R.drawable.riba5,""));
            dataList.add(new ListItem("Danio ribe", R.drawable.riba6,""));
            dataList.add(new ListItem("Anđeoska riba", R.drawable.riba7,""));
            dataList.add(new ListItem("Diskus riba", R.drawable.riba8,""));
            dataList.add(new ListItem("Platy", R.drawable.riba9,""));
            dataList.add(new ListItem("Sumatranski borac", R.drawable.riba10,""));
        } else {
            Toast.makeText(this, "Nepoznata kategorija", Toast.LENGTH_SHORT).show();
            finish();
        }
        return dataList;
    }

    private void showDetailsActivity(ListItem selectedItem) {
        Intent intent = new Intent(this, DetailActivity.class);
        intent.putExtra("imageResource", selectedItem.getImageResourceId());
        intent.putExtra("text", selectedItem.getName());
        intent.putExtra("description", selectedItem.getDescription());


        startActivity(intent);
    }

}
